# Generated by Django 5.0 on 2023-12-07 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TruckDetail',
            fields=[
                ('truck_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('location_description', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('food_items', models.TextField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
            options={
                'db_table': 'trucks',
            },
        ),
    ]
