# Generated by Django 5.0 on 2023-12-06 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='truck_detail',
            fields=[
                ('truck_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('location_description', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('food_items', models.TextField()),
                ('latitude', models.DecimalField(decimal_places=3, max_digits=8)),
                ('longitude', models.DecimalField(decimal_places=3, max_digits=8)),
            ],
        ),
    ]
