# Generated by Django 5.0 on 2023-12-06 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_truck_locator_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='truck_detail',
            name='latitude',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name='truck_detail',
            name='longitude',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
    ]
