# Generated by Django 5.0 on 2023-12-06 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_truck_locator_api', '0002_alter_truck_detail_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='truck_detail',
            name='latitude',
            field=models.DecimalField(decimal_places=8, max_digits=10, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='truck_detail',
            name='longitude',
            field=models.DecimalField(decimal_places=8, max_digits=11, verbose_name='Longitude'),
        ),
    ]
