# Generated by Django 5.0 on 2023-12-06 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_truck_locator_api', '0003_alter_truck_detail_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='truck_detail',
            name='latitude',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='truck_detail',
            name='longitude',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Latitude'),
        ),
    ]
